"""empty message

Revision ID: 2347c44a788c
Revises: c1a9ec66002c
Create Date: 2021-04-20 13:34:14.247890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2347c44a788c'
down_revision = 'c1a9ec66002c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_id')
    # ### end Alembic commands ###
