"""empty message

Revision ID: 4e087f4bfb10
Revises: 6895e8e79601
Create Date: 2021-04-20 00:22:01.984438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e087f4bfb10'
down_revision = '6895e8e79601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('issue', sa.Integer(), nullable=False))
    op.add_column('comments', sa.Column('user', sa.String(), nullable=False))
    op.drop_constraint('comments_issue_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'issues', ['issue'], ['id'])
    op.create_foreign_key(None, 'comments', 'users', ['user'], ['id'])
    op.drop_column('comments', 'user_id')
    op.drop_column('comments', 'issue_id')
    op.add_column('issues', sa.Column('user', sa.String(), nullable=False))
    op.drop_constraint('issues_user_id_fkey', 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['user'], ['id'])
    op.drop_column('issues', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key('issues_user_id_fkey', 'issues', 'users', ['user_id'], ['id'])
    op.drop_column('issues', 'user')
    op.add_column('comments', sa.Column('issue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('comments', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key('comments_issue_id_fkey', 'comments', 'issues', ['issue_id'], ['id'])
    op.drop_column('comments', 'user')
    op.drop_column('comments', 'issue')
    # ### end Alembic commands ###
