"""empty message

Revision ID: c1a9ec66002c
Revises: 0eb7d84d7591
Create Date: 2021-04-20 11:32:11.267968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1a9ec66002c'
down_revision = '0eb7d84d7591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.drop_column('users', 'date_joined')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
