"""empty message

Revision ID: c403428e7fa5
Revises: 9449f069b564
Create Date: 2021-04-16 16:36:36.521666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c403428e7fa5'
down_revision = '9449f069b564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('roles', sa.ARRAY(sa.String(length=100)), nullable=True))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('users', 'roles')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
